(() => {
  'use strict';
  const {Game,TYPES,TYPE_MAP,RIVALS,BRANCHES,SKILLS,SKILL_MAP,LANDMARKS,STAGES,MAP_LABELS,cameraFrame,clamp}=FengdouEngine;
  const RIVAL_CROPS=[[64,13,324,505],[471,19,263,502],[826,13,266,506],[1210,18,258,502],[76,521,275,497],[435,620,315,376],[825,578,264,429],[1192,518,304,496]];
  const game=new Game();
  const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d');
  const overlay=$('overlay'),dialog=$('dialog');
  const assets={};let assetsReady=false,selected='future',sound=false,audioCtx=null,modal='start',helpReturn=null,oldFocus=null;
  let zoomIndex=1,expanded=false;const ZOOM_STEPS=[.8,1,1.25,1.5];
  const miniCtx=$('minimap').getContext('2d');
  let view={w:1000,h:680,scale:.8,x:0,y:0,visibleWidth:1250,visibleHeight:850},frameTime=0,uiClock=0,announcementTimer=0,damageFlash=0;
  let pointer=null,stick={x:0,y:0},keys=new Set(),best=0,crewSignature='',skillSignature='',landmarkSignature='',trackedLandmark='tianshan';
  try{best=Math.max(0,Number(localStorage.getItem('fengdou-yuzhong-best'))||0);}catch{}
  $('best').textContent=best;
  const announcement=text=>{$('announcement').textContent=text;$('announcement').classList.add('visible');announcementTimer=3;$('live-status').textContent=text;};
  function beep(freq=600,duration=.07,type='sine',volume=.06){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const osc=audioCtx.createOscillator(),gain=audioCtx.createGain();osc.type=type;osc.frequency.value=freq;gain.gain.setValueAtTime(volume,audioCtx.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+duration);osc.connect(gain);gain.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+duration);}catch{}}
  function chime(){beep(523,.12);setTimeout(()=>beep(659,.12),75);setTimeout(()=>beep(784,.18),150);}
  function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(r.width*dpr);canvas.height=Math.round(r.height*dpr);view.w=r.width;view.h=r.height;ctx.setTransform(dpr,0,0,dpr,0,0);}
  new ResizeObserver(resize).observe($('arena'));
  function changeZoom(delta){zoomIndex=clamp(zoomIndex+delta,0,ZOOM_STEPS.length-1);$('zoom-label').textContent=Math.round(ZOOM_STEPS[zoomIndex]*100)+'%';$('zoom-out').disabled=zoomIndex===0;$('zoom-in').disabled=zoomIndex===ZOOM_STEPS.length-1;keys.clear();releasePointer();canvas.focus({preventScroll:true});}
  function toggleExpanded(force){expanded=typeof force==='boolean'?force:!expanded;$('arena').classList.toggle('expanded',expanded);document.body.classList.toggle('game-expanded',expanded);$('expanded-close').hidden=!expanded;$('expand-btn').setAttribute('aria-pressed',String(expanded));$('expand-btn').setAttribute('aria-label',expanded?'收起游戏画面':'放大游戏画面');keys.clear();releasePointer();resize();if(!modal)canvas.focus({preventScroll:true});else dialog.querySelector('button:not(:disabled)')?.focus({preventScroll:true});}
  function drawMinimap(){const w=300,h=200,c=miniCtx;c.clearRect(0,0,w,h);if(assets.map)c.drawImage(assets.map,0,0,w,h);else{c.fillStyle='#729368';c.fillRect(0,0,w,h);}c.fillStyle='#122e2c55';c.fillRect(0,0,w,h);const sx=w/game.width,sy=h/game.height;c.fillStyle='#ffefb328';c.fillRect(view.x*sx,view.y*sy,view.visibleWidth*sx,view.visibleHeight*sy);c.strokeStyle='#fff3ba';c.lineWidth=2;c.strokeRect(view.x*sx,view.y*sy,view.visibleWidth*sx,view.visibleHeight*sy);for(const m of game.meetups){if(m.used)continue;c.fillStyle='#f5fbe4';c.beginPath();c.arc(m.x*sx,m.y*sy,3,0,Math.PI*2);c.fill();}for(const m of game.landmarks){c.fillStyle=m.state==='complete'?'#a4b29b':m.color;c.strokeStyle=m.id===trackedLandmark?'#fff3a5':'#16372a';c.lineWidth=2;c.beginPath();c.arc(m.x*sx,m.y*sy,m.id===trackedLandmark?6:4,0,Math.PI*2);c.fill();c.stroke();}c.fillStyle='#ffe061';c.strokeStyle='#174337';c.lineWidth=2;c.beginPath();c.arc(game.player.x*sx,game.player.y*sy,5,0,Math.PI*2);c.fill();c.stroke();}

  function openModal(type,html,css=''){oldFocus=document.activeElement;modal=type;overlay.hidden=false;dialog.className='dialog '+css;dialog.innerHTML=html;dialog.scrollTop=0;const arenaRect=$('arena').getBoundingClientRect();if(arenaRect.top<0||arenaRect.top>innerHeight*.4)$('arena').scrollIntoView({block:'center'});keys.clear();releasePointer();requestAnimationFrame(()=>{const b=dialog.querySelector('button:not(:disabled)');b?.focus({preventScroll:true});});}
  function closeModal(){overlay.hidden=true;modal=null;keys.clear();releasePointer();canvas.focus({preventScroll:true});}
  const starString=n=>'★'.repeat(n)+'☆'.repeat(3-n);
  function startScreen(){game.reset();crewSignature='';skillSignature='';landmarkSignature='';trackedLandmark='tianshan';updateUI();$('map-caption').hidden=false;$('pause-btn').disabled=true;$('dash-btn').disabled=true;$('boss-hud').hidden=true;openModal('start',`
      <img class="start-hero" src="assets/fengdou.png" alt="照片原型改编的 Fengdou"><span class="sticker">Fengdou，出门啦！</span>
      <p class="dialog-kicker">FENGDOU × 兰州大学榆中校区</p><h2 id="dialog-title">一个人开局，<br><em>一群搭子通关。</em></h2>
      <p class="desc">大校园，慢慢逛。三关冒险，每关 3 分钟。<br>找搭子、捡默契星，把三系技能一路养起来。</p>
      <div class="journey-strip"><span>01 白天校园</span><i>→</i><span>02 傍晚公园</span><i>→</i><span>03 榆中不眠夜</span></div><div class="start-label">先约谁出门？<span>搭子自动出招，你只管走位</span></div>
      <div class="starter-options">${['future','jade','yiting'].map(id=>{const t=TYPE_MAP[id];return `<button class="starter ${selected===id?'selected':''}" data-starter="${id}" aria-pressed="${selected===id}"><span class="emoji">${t.icon}</span><strong>${t.name}</strong><small>${t.skill}</small></button>`;}).join('')}</div>
      <button class="primary" id="start-button" ${assetsReady?'':'disabled'}>${assetsReady?'出发！今天不鸽':'正在准备校园…'}</button>
      <p class="start-foot">WASD / 方向键 · 空格疾走 · 手机拖动</p><button class="intro-link" id="intro-button">交友宣言 · 人物技能 · 校园奇遇</button>`, 'start');
    dialog.querySelectorAll('[data-starter]').forEach(b=>b.onclick=()=>{selected=b.dataset.starter;dialog.querySelectorAll('[data-starter]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});beep(440);});
    $('start-button').onclick=startRun;$('intro-button').onclick=atlas;
  }
  function startRun(){if(!assetsReady)return;game.start(selected);trackedLandmark=game.stage.landmark;closeModal();$('map-caption').hidden=true;$('pause-btn').disabled=false;$('dash-btn').disabled=false;announcement('第 1 关 · 校园初遇：先找搭子，再去天山堂看看！');chime();updateUI();}
  function showChoices(){const meeting=game.options[0]?.kind==='buddy';openModal('upgrade',`<p class="dialog-kicker">${meeting?'好巧，你也在这里！':'FENGDOU · 成长时刻'}</p><h2 id="dialog-title">${meeting?'新搭子，来一个！':'这次练哪一招？'}</h2><p class="desc">${game.offerReason} · 选择时游戏暂停</p><div class="upgrade-options">${game.options.map((o,i)=>{const b=BRANCHES.find(b=>b.id===o.branch);return `<button class="upgrade-card ${b?'branch-'+b.id:''}" data-choice="${i}"><kbd>${i+1}</kbd><span class="emoji">${o.icon}</span><span class="card-label">${b?b.name+'系列':o.kind==='buddy'?(o.nextLevel===1?'邀请入队':'默契进阶'):'即刻生效'}${o.nextLevel?' · '+starString(o.nextLevel):''}</span><strong>${o.name}</strong><p>${o.desc}</p></button>`;}).join('')}</div>`, 'upgrade');dialog.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.choice)));}
  function choose(index){if(game.status!=='upgrade')return;const o=game.choose(index);closeModal();chime();announcement((o.kind==='skill'?BRANCHES.find(b=>b.id===o.branch).name+' · ':'')+o.name+(o.nextLevel?' '+starString(o.nextLevel):''));updateUI();}
  function rememberReturn(){if(!['help','atlas','places'].includes(modal))helpReturn={modal,status:game.status};if(game.status==='running')game.pause();}
  function landmarkCatalogue(){return `<section class="skill-catalogue"><h3>三处校园奇遇 · 每关每处一次</h3><div class="place-catalogue">${LANDMARKS.map(m=>`<div class="place-card"><span>${m.icon}</span><div><strong>${m.name}</strong><small>${m.desc}</small></div></div>`).join('')}</div></section>`;}
  function placesGuide(){rememberReturn();openModal('places',`<p class="dialog-kicker">榆中校园 · 奇遇地图</p><h2 id="dialog-title">来都来了，去看看。</h2><p class="desc">黄点是你，亮框是当前视野。跟着路标找搭子。</p><div class="map-overview" aria-label="三个校园奇遇的位置示意">${LANDMARKS.map((m,i)=>`<span class="overview-pin" style="left:${m.x/game.width*100}%;top:${m.y/game.height*100}%">${m.icon}<b>${i+1}</b></span>`).join('')}${game.status!=='ready'?`<span class="overview-viewport" style="left:${view.x/game.width*100}%;top:${view.y/game.height*100}%;width:${view.visibleWidth/game.width*100}%;height:${view.visibleHeight/game.height*100}%"></span><span class="overview-you" style="left:${game.player.x/game.width*100}%;top:${game.player.y/game.height*100}%" aria-label="你在这里"></span>`:''}</div><div class="place-catalogue">${game.landmarks.map((m,i)=>`<div class="place-card"><span>${m.icon}</span><div><strong>${i+1}. ${m.name}</strong><small>${m.desc}</small><button class="text-btn" data-track="${m.id}" ${m.state==='complete'||game.status==='ready'?'disabled':''}>${m.state==='complete'?'本关已完成 ✓':game.status==='ready'?'出发后可以标记方向':'标记这个地点 →'}</button></div></div>`).join('')}</div><p class="map-credit">卡通校园，地点位置按玩法安排。</p><button class="primary" id="close-places">记住了，出发</button>`,'places');$('close-places').onclick=restoreHelp;dialog.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{trackedLandmark=b.dataset.track;landmarkSignature='';restoreHelp();announcement('已标记：'+LANDMARKS.find(m=>m.id===trackedLandmark).title);});}
  function showLandmark(){const m=game.currentLandmark;if(!m)return;const stalls=m.id==='tianshan'?`<div class="stalls" aria-label="进门后的六个坑位">${[1,2,3,4,5,6].map(n=>`<span class="${n>4?'available':''}">${n}<small>${n>4?'就是它？':'路过'}</small></span>`).join('')}</div>`:'';openModal('landmark',`<p class="dialog-kicker">发现校园奇遇 · ${m.tag}</p><h2 id="dialog-title">${m.title}</h2><p class="place-fullname">${m.name}</p>${stalls}<p class="desc">${m.id==='yuzhong'&&!game.landmarkOptions.length?'本关剩余时间不足 12 秒，下关再来挑战。':m.desc}<br>选择期间暂停 · 奖励每关限领一次</p><div class="upgrade-options landmark-options">${game.landmarkOptions.map((o,i)=>`<button class="upgrade-card" data-place-choice="${i}"><kbd>${i+1}</kbd><span class="emoji">${o.icon}</span><strong>${o.name}</strong><p>${o.desc}</p></button>`).join('')}</div><button class="secondary" id="leave-place">先走了，下次再来</button>`,'landmark');dialog.querySelectorAll('[data-place-choice]').forEach(b=>b.onclick=()=>chooseLandmark(Number(b.dataset.placeChoice)));$('leave-place').onclick=leaveLandmark;}
  function chooseLandmark(index){if(game.status!=='landmark')return;game.chooseLandmark(index);closeModal();landmarkSignature='';updateUI();}
  function leaveLandmark(){if(game.leaveLandmark()){closeModal();announcement('先去逛逛，离开路标后还能回来。');}}
  function stageClearScreen(){const next=STAGES[game.stageIndex+1];openModal('stage-clear',`<p class="dialog-kicker">第 ${game.stageIndex+1} 关 · 生存达标</p><h2 id="dialog-title">${game.stage.name}，过关！</h2><p class="desc">队伍已集合，下一站：${next.scene}。<br>全部技能、搭子与经验保留，恢复 35 电量。</p><div class="journey-strip">${STAGES.map((s,i)=>`<span class="${i<=game.stageIndex?'done':''}">${i<=game.stageIndex?'✓':'0'+(i+1)} ${s.name}</span>`).join('')}</div><div class="next-stage"><span>${next.id==='park'?'🌅':'🌙'}</span><strong>第 ${game.stageIndex+2} 关 · ${next.name}</strong><p>${next.subtitle}<br>关底对手：${RIVALS[next.boss].name}</p></div><button class="primary" id="next-stage-button">带上搭子，前往下一关 →</button><button class="secondary" id="leave-run">结束冒险，返回出发页</button>`,'stage-clear');$('next-stage-button').onclick=()=>{game.nextStage();closeModal();$('pause-btn').disabled=false;$('dash-btn').disabled=false;updateUI();};$('leave-run').onclick=startScreen;$('pause-btn').disabled=true;$('dash-btn').disabled=true;}
  function updateJourney(){
    $('chapter-title').textContent=game.stage.scene;$('chapter-count').textContent=String(game.stageIndex+1).padStart(2,'0')+' / 03';$('chapter-goal').textContent=game.status==='ready'?'每关 3 分钟 · 技能和搭子延续':game.phase===3?'关底：'+RIVALS[game.stage.boss].name+' · 存活即可过关':['先探索，组好你的小队','攻势增强，边走边捡默契星','最后一分钟，守住电量'][game.phase];
    const stageSig=game.stageIndex+':'+game.completedStages.length;
    if($('chapter-route').dataset.signature!==stageSig){$('chapter-route').dataset.signature=stageSig;$('chapter-route').innerHTML=STAGES.map((s,i)=>`<span class="${i===game.stageIndex?'current':''} ${i<game.completedStages.length?'done':''}"><b>${i<game.completedStages.length?'✓':i+1}</b>${s.name}</span>`).join('');}
    $('minimap-button').hidden=game.status==='ready';$('xp-label').textContent='默契 '+game.xp+' / '+game.need;
    const sig=game.landmarks.map(m=>m.id+':'+m.state).join('|')+':'+trackedLandmark;if(sig!==landmarkSignature){landmarkSignature=sig;$('landmark-count').textContent=game.landmarks.filter(m=>m.state==='complete').length+' / 3';$('landmark-list').innerHTML=game.landmarks.map(m=>`<button class="landmark-row ${m.id===trackedLandmark?'tracked':''} ${m.state==='complete'?'complete':''}" data-landmark="${m.id}" aria-label="${m.name}，${m.state==='complete'?'本关已完成':'标记方向'}"><span>${m.icon}</span><div><strong>${m.mapName}</strong><small>${m.state==='complete'?'本关已完成':m.state==='active'?'挑战进行中':m.tag}</small></div><b>${m.state==='complete'?'✓':m.id===trackedLandmark?'➤':'↗'}</b></button>`).join('');$('landmark-list').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(game.status==='ready'){placesGuide();return;}const m=game.landmarks.find(m=>m.id===b.dataset.landmark);if(m.state==='complete'){announcement('这里的奖励本关已经领过，下关再来。');return;}trackedLandmark=m.id;landmarkSignature='';announcement('跟着箭头去：'+m.title);});}
    $('challenge-hud').hidden=!game.challenge;if(game.challenge){$('challenge-label').textContent='👻 榆中挑战 · 再坚持 '+game.challenge.remaining.toFixed(1)+' 秒';$('challenge-bar').style.width=((1-game.challenge.remaining/game.challenge.duration)*100)+'%';}
    let target=game.landmarks.find(m=>m.id===trackedLandmark&&m.state!=='complete');if(!target&&game.status==='running'){target=game.landmarks.filter(m=>m.state!=='complete').sort((a,b)=>Math.hypot(a.x-game.player.x,a.y-game.player.y)-Math.hypot(b.x-game.player.x,b.y-game.player.y))[0];if(target){trackedLandmark=target.id;landmarkSignature='';}}
    $('navigation').hidden=game.status!=='running'||!target;if(target){$('nav-label').textContent=target.icon+' '+target.mapName;$('nav-arrow').style.transform='rotate('+Math.atan2(target.y-game.player.y,target.x-game.player.x)+'rad)';}
  }
  function drawLandmarks(){for(const m of game.landmarks){const done=m.state==='complete',pulse=1+Math.sin(frameTime*.0028)*.08;ctx.save();if(m.id==='yuzhong'&&game.challenge){ctx.fillStyle='#b39bdd22';ctx.strokeStyle='#dbc0f299';ctx.lineWidth=3;ctx.beginPath();ctx.arc(m.x,m.y,155,0,Math.PI*2);ctx.fill();ctx.stroke();}ctx.globalAlpha=done?.65:1;ctx.fillStyle=done?'#edf1d3aa':m.color+'55';ctx.beginPath();ctx.arc(m.x,m.y,38*pulse,0,Math.PI*2);ctx.fill();ctx.strokeStyle=m.id===trackedLandmark?'#fff4b6':m.color;ctx.lineWidth=m.id===trackedLandmark?4:2;ctx.beginPath();ctx.arc(m.x,m.y,31,0,Math.PI*2);ctx.stroke();emoji(done?'✓':m.icon,m.x,m.y-2,27);label(m.mapName+(done?' ✓':''),m.x,m.y+35,done?'#788264':'#544362',11);ctx.restore();}}
  function pauseScreen(){if(game.status!=='running')return;game.pause();openModal('pause',`<p class="dialog-kicker">歇一会儿，不算鸽</p><h2 id="dialog-title">搭子等你回来。</h2><p class="desc">剩余 ${Math.ceil(game.duration-game.time)} 秒 · 已结识 ${game.team.length} 位搭子<br>第 ${game.stageIndex+1} / 3 关 · ${game.stage.name}<br>技能与搭子会带入下一关。</p><button class="primary" id="resume-button">继续这局</button><button class="secondary" id="restart-button">重新选搭子</button>`);$('resume-button').onclick=()=>{game.resume();closeModal();};$('restart-button').onclick=startScreen;}
  function help(){if(modal==='help'){restoreHelp();return;}rememberReturn();openModal('help',`<p class="dialog-kicker">榆中搭子生存手册</p><h2 id="dialog-title">不鸽，就是胜利。</h2><div class="help-list"><div><b>① 出门走位</b><br>WASD / 方向键移动；手机或鼠标按住画面拖动。空格或「疾走」短暂无敌冲刺。按 F 放大游戏画面；加减号调整视野，按 M 查看校园全图。</div><div><b>② 找到你的搭子</b><br>走进发光的集合点，邀请未来搭子、碧玉妹妹、王逸婷。三位搭子各有技能。</div><div><b>③ 三系自由混搭</b><br>击退对手会掉默契星，靠近自动拾取。升级时在斐济被、青训、精神病爆发三系中三选一，每招最多三级，越往后所需默契越多。</div><div><b>④ 三关连续冒险</b><br>每关坚持 3 分钟，技能与搭子带入下一关，过关恢复 35 电量。最后 30 秒出现关底对手：kakax、竹节人冯子恩、银泉火旺。存活即可过关，击退关底对手额外加分。</div><div><b>⑤ 路过校园奇遇</b><br>天山堂选第五／第六坑位，袁山公园旁补给，榆中👻地带坚持十秒拿奖励。每关每处可领取一次；点击「校园奇遇」的地点可标记方向。</div></div><p class="map-credit">地图参考<a href="https://yuzhong.lzu.edu.cn/xiaoquzonglan/xiaoqudaoshi/2018/1227/213888.html" target="_blank" rel="noopener">校方榆中校区导示图</a>作卡通简绘，局部道路和建筑为玩法压缩。</p><button class="primary" id="close-help">明白，搭子集合！</button>`,'help');$('close-help').onclick=restoreHelp;}
  function restoreHelp(){const prev=helpReturn;helpReturn=null;if(prev?.status==='running'){game.resume();closeModal();}else if(prev?.status==='upgrade')showChoices();else if(prev?.status==='landmark')showLandmark();else if(prev?.status==='stage-clear')stageClearScreen();else if(prev?.status==='won'||prev?.status==='lost')endScreen();else if(prev?.status==='paused'){game.resume();pauseScreen();}else startScreen();}
  function portraitStyle(i){const c=RIVAL_CROPS[i],scale=58/c[3];return `width:${Math.ceil(c[2]*scale)}px;height:58px;background-size:${1536*scale}px ${1024*scale}px;background-position:${-c[0]*scale}px ${-c[1]*scale}px`; }
  function atlas(){rememberReturn();openModal('atlas',`<p class="dialog-kicker">FENGDOU 的搭子招募宣言</p><h2 id="dialog-title">有空，一起玩。</h2><blockquote>“学习，桌游，麻将，剧本杀等等，健身，跑步，爬山，游泳，羽毛球，就单纯交友聊天侃大山也行。”</blockquote><div class="atlas-grid">${TYPES.map(t=>`<div class="atlas-card"><span>${t.icon}</span><div><strong>${t.name}</strong><small>${t.skill} · ${t.desc}</small><p>“${t.quote}”</p></div></div>`).join('')}</div><section class="skill-catalogue"><h3>校园对手图鉴</h3><div class="atlas-grid">${RIVALS.map(r=>`<div class="atlas-card"><span class="rival-portrait" style="${portraitStyle(r.sprite)}" role="img" aria-label="${r.name}卡通形象"></span><div><strong>${r.name}</strong><small>${r.desc}</small></div></div>`).join('')}</div></section><section class="skill-catalogue"><h3>Fengdou 的三系技能 · 每招可升三级</h3><div class="skill-catalogue-grid">${BRANCHES.map(b=>`<div class="skill-catalogue-group"><strong>${b.icon} ${b.name}</strong>${SKILLS.filter(s=>s.branch===b.id).map(s=>`<p>${s.icon} ${s.name}</p><small>${s.desc}</small>`).join('')}</div>`).join('')}</div></section>${landmarkCatalogue()}<button class="primary" id="close-atlas">好，出门找搭子</button>`,'atlas');$('close-atlas').onclick=restoreHelp;}
  function endScreen(){const win=game.status==='won',score=game.score,isNew=score>best;if(isNew){best=score;try{localStorage.setItem('fengdou-yuzhong-best',String(best));}catch{}}$('pause-btn').disabled=true;$('dash-btn').disabled=true;const branchScores=BRANCHES.map(b=>({...b,total:Object.entries(game.skills).filter(([id])=>SKILL_MAP[id].branch===b.id).reduce((n,[,lv])=>n+lv,0)})).sort((a,b)=>b.total-a.total);const title=win?(game.team.length>=3?'榆中社交天花板':game.bossKilled?'校园闯关王':'今天真的没白出门'):'歇口气，下次再约';openModal('end',`<p class="result-label">${win?'✦ 搭子集结成功 ✦':'今天的社交电量用完了'}</p><h2 id="dialog-title">${title}</h2><img class="results-portrait" src="assets/fengdou.png" alt="Fengdou"><div class="result-stats"><div><strong>${score}</strong><span>${isNew?'新纪录！':'本局得分'}</span></div><div><strong>${Math.floor(game.elapsed)}s</strong><span>坚持时间</span></div><div><strong>${game.team.length}</strong><span>结识搭子</span></div></div><div class="result-crew">${game.team.map(c=>TYPE_MAP[c.id].icon).join('')}</div><p class="desc result-desc">${branchScores[0].total?`本局主修「${branchScores[0].name}」 · `:''}击退 ${game.kills} 位对手${game.bossesKilled?' · 击退 '+game.bossesKilled+' 位关底对手':''}<br>已完成 ${game.completedStages.length} / 3 关 · 奇遇奖励 ${game.landmarkBonus} 分<br>${win?'从白天到深夜，这次谁都没鸽。':'换条路线，也许下一局就能走到最后。'}</p><button class="primary" id="again-button">再来一局，换种搭法</button><button class="secondary" id="back-button">回到出发页</button>`,'result');$('again-button').onclick=startRun;$('back-button').onclick=startScreen;updateUI();if(win)chime();else beep(180,.25);}
  function updateUI(){const p=game.player;const remain=Math.max(0,Math.ceil(game.duration-game.time));$('timer').textContent=String(Math.floor(remain/60)).padStart(2,'0')+':'+String(remain%60).padStart(2,'0');$('phase-label').textContent='第 '+(game.stageIndex+1)+' / 3 关 · '+game.stage.name;$('level').textContent='LV. '+game.level;$('health-bar').style.width=(p.hp/p.maxHp*100)+'%';$('health-bar').style.background=p.hp/p.maxHp<.3?'#ce7164':'#31845f';$('health-label').textContent='社交电量 '+Math.ceil(p.hp)+' / '+p.maxHp+(game.shield?' · 盾'+game.shield:'');$('xp-bar').style.width=Math.min(100,game.xp/game.need*100)+'%';$('kills').textContent=game.kills;$('best').textContent=best;$('crew-count').textContent=(game.team.length+1)+' / 4';$('dash-cooldown').style.transform='scaleY('+clamp(p.dashCooldown/3.3,0,1)+')';$('dash-btn').querySelector('small').textContent=p.dashCooldown>0?p.dashCooldown.toFixed(1)+'s':'SPACE';const boss=game.enemies.find(e=>e.type==='boss');$('boss-hud').hidden=!boss||game.status==='ready';if(boss){$('boss-bar').style.width=(boss.hp/boss.maxHp*100)+'%';$('boss-title').textContent='关底对手 · '+boss.name;}updateJourney();
    const sig=JSON.stringify(game.team.map(c=>[c.id,c.level]));if(sig!==crewSignature){crewSignature=sig;$('crew-list').innerHTML=`<div class="crew-row"><div class="crew-avatar"><img src="assets/fengdou.png" alt=""></div><div><strong>Fengdou</strong><small>今天这局，我来组</small></div><b>队长</b></div>`+game.team.map(c=>{const t=TYPE_MAP[c.id];return `<div class="crew-row"><div class="crew-avatar" style="background:${t.color}33">${t.icon}</div><div><strong>${t.name}</strong><small>${t.skill}</small></div><b>${'★'.repeat(c.level)}</b></div>`;}).join('')+Array.from({length:3-game.team.length},(_,i)=>`<div class="crew-row empty"><div class="crew-avatar">＋</div><div><strong>虚位以待</strong></div></div>`).join('');const syn=game.synergies;$('synergy').classList.toggle('active',syn.length>0);$('synergy').innerHTML='<span>✦ 默契加成</span><p>'+(syn.length?syn.map(s=>s.desc).join('<br>'):'两位搭子加快出招，三位到齐再加伤害和恢复。')+'</p>';}
    const ss=JSON.stringify(game.skills);if(ss!==skillSignature){skillSignature=ss;$('skill-list').innerHTML=BRANCHES.map(b=>{const trained=Object.entries(game.skills).filter(([id])=>SKILL_MAP[id].branch===b.id);return `<div class="skill-row" style="--branch:${b.color}"><span>${b.icon}</span><div><strong>${b.name}</strong><small>${trained.length?trained.map(([id,n])=>SKILL_MAP[id].name+' '+('★'.repeat(n))).join(' · '):b.tag}</small></div><b>${trained.reduce((s,[,n])=>s+n,0)||'—'}</b></div>`;}).join('');}}
  function releasePointer(){pointer=null;stick={x:0,y:0};$('joystick').classList.remove('active');}
  function input(){let x=(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);if(pointer){x=stick.x;y=stick.y;}return{x,y};}
  canvas.addEventListener('pointerdown',e=>{if(game.status!=='running')return;e.preventDefault();canvas.setPointerCapture(e.pointerId);const r=canvas.getBoundingClientRect();pointer={id:e.pointerId,x:e.clientX,y:e.clientY};stick={x:0,y:0};$('joystick').style.left=(e.clientX-r.left-46)+'px';$('joystick').style.top=(e.clientY-r.top-46)+'px';$('joystick').querySelector('i').style.transform='translate(0,0)';$('joystick').classList.add('active');});
  canvas.addEventListener('pointermove',e=>{if(!pointer||e.pointerId!==pointer.id)return;const dx=e.clientX-pointer.x,dy=e.clientY-pointer.y,len=Math.hypot(dx,dy),scale=Math.min(1,34/(len||1));stick={x:clamp(dx/35,-1,1),y:clamp(dy/35,-1,1)};$('joystick').querySelector('i').style.transform=`translate(${dx*scale}px,${dy*scale}px)`;});
  for(const event of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(event,releasePointer);
  window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key==='f'&&!e.repeat){e.preventDefault();toggleExpanded();return;}if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(key))e.preventDefault();if(modal){if(key==='tab'){const buttons=[...dialog.querySelectorAll('button:not(:disabled),a[href]')];if(buttons.length){const first=buttons[0],last=buttons[buttons.length-1];if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}}if(!e.repeat&&modal==='upgrade'&&['1','2','3'].includes(key)&&game.options[Number(key)-1])choose(Number(key)-1);if(!e.repeat&&modal==='landmark'&&['1','2','3'].includes(key)&&game.landmarkOptions[Number(key)-1])chooseLandmark(Number(key)-1);if(key==='escape'&&modal==='landmark')leaveLandmark();if((key==='escape'||key==='p')&&modal==='pause'){game.resume();closeModal();}else if(key==='escape'&&(modal==='help'||modal==='atlas'||modal==='places'))restoreHelp();return;}if(key==='escape'&&expanded&&!e.repeat){toggleExpanded(false);return;}if(key==='m'&&!e.repeat){placesGuide();return;}if((key==='+'||key==='=')&&!e.repeat){changeZoom(1);return;}if(key==='-'&&!e.repeat){changeZoom(-1);return;}if((key==='p'||key==='escape')&&!e.repeat){pauseScreen();return;}if(key===' '&&!e.repeat){if(game.dash())beep(350,.1,'triangle');}keys.add(key);});
  window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
  window.addEventListener('blur',()=>{keys.clear();releasePointer();if(game.status==='running')pauseScreen();});
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.status==='running')pauseScreen();});
  $('pause-btn').onclick=()=>{if(game.status==='running')pauseScreen();};$('dash-btn').onclick=()=>{if(game.dash())beep(350,.1,'triangle');};$('zoom-in').onclick=()=>changeZoom(1);$('zoom-out').onclick=()=>changeZoom(-1);$('expand-btn').onclick=()=>toggleExpanded();$('expanded-close').onclick=()=>toggleExpanded(false);$('minimap-button').onclick=placesGuide;$('help-btn').onclick=help;$('places-btn').onclick=placesGuide;$('navigation').onclick=placesGuide;$('atlas-btn').onclick=atlas;
  $('sound-btn').onclick=()=>{sound=!sound;$('sound-btn').setAttribute('aria-label',sound?'关闭音效':'开启音效');$('sound-btn').title=sound?'关闭音效':'开启音效';$('sound-btn').querySelector('span').textContent=sound?'音效开':'音效关';beep(520,.12);};
  function rounded(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);}
  function label(text,x,y,color='#264d3a',font=13){ctx.font=`600 ${font}px "Noto Sans SC",sans-serif`;const tw=ctx.measureText(text).width;rounded(x-tw/2-10,y-11,tw+20,23,7);ctx.fillStyle='#fffef0e5';ctx.fill();ctx.fillStyle=color;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,x,y+1);}
  function sprite(img,sx,sy,sw,sh,x,y,w,h,flip=false){if(!img)return;ctx.save();ctx.translate(x,y);if(flip)ctx.scale(-1,1);ctx.drawImage(img,sx,sy,sw,sh,-w/2,-h,w,h);ctx.restore();}
  function emoji(txt,x,y,size=30){ctx.font=`${size}px "Apple Color Emoji","Segoe UI Emoji",sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(txt,x,y);}
  function shadow(x,y,w=22){ctx.fillStyle='#19392c2c';ctx.beginPath();ctx.ellipse(x,y+3,w,7,0,0,Math.PI*2);ctx.fill();}
  function drawHero(x,y,moving){const p=game.player;shadow(x,y,19);if(game.shield||p.invincible>0||game.frenzy>0){ctx.strokeStyle=game.frenzy>0?'#f298d4':game.shield?'#a4fff0':'#fff7a3';ctx.lineWidth=3;ctx.globalAlpha=.7;ctx.beginPath();ctx.ellipse(x,y-26,32,47,0,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}ctx.globalAlpha=p.invincible>0&&Math.floor(game.time*18)%2===0?.6:1;const bob=moving?Math.sin(game.time*18)*3:Math.sin(frameTime*.0018)*1.4;sprite(assets.hero,350,0,530,1254,x,y+bob,38,90,p.dx<0);ctx.globalAlpha=1;label('Fengdou',x,y+19,'#245b40',12);}
  function drawCompanion(c,i){const t=TYPE_MAP[c.id],pos=game.companionPosition(i),col=t.sprite%3,row=Math.floor(t.sprite/3);shadow(pos.x,pos.y,17);sprite(assets.companions,col*512,row*512,512,512,pos.x,pos.y+Math.sin(game.time*5+i)*2,62,62);emoji(t.icon,pos.x+20,pos.y-58,17);}
  function drawEnemy(e){const rival=RIVALS[e.roster],boss=e.type==='boss',w=boss?104:60,h=boss?128:76;shadow(e.x,e.y,boss?31:17);if(e.boost>0){ctx.fillStyle=rival.color+'66';ctx.beginPath();ctx.ellipse(e.x,e.y-12,23,12,0,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=e.hit>0?.6:1;if(assets.rivals){const c=RIVAL_CROPS[e.roster];ctx.save();ctx.translate(e.x,e.y+Math.sin(game.time*8+e.phase)*2);if(e.roster===6)ctx.rotate(Math.sin(game.time*12+e.phase)*.085);sprite(assets.rivals,...c,0,0,h*c[2]/c[3],h,e.x>game.player.x);ctx.restore();}else emoji(rival.icon,e.x,e.y-20,boss?65:37);ctx.globalAlpha=1;if(boss)emoji('👑',e.x,e.y-h+6,27);label(rival.name,e.x,e.y+15,boss?'#a45e40':'#675f57',boss?15:11);if(e.hp<e.maxHp&&!boss){ctx.fillStyle='#34544970';ctx.fillRect(e.x-18,e.y-72,36,4);ctx.fillStyle=rival.color;ctx.fillRect(e.x-18,e.y-72,36*e.hp/e.maxHp,4);}}
  function render(){const {w,h}=view,dpr=Math.min(devicePixelRatio||1,2);ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const active=game.status!=='ready';const focus=game.player;Object.assign(view,cameraFrame(w,h,focus,ZOOM_STEPS[zoomIndex]));const {scale}=view;ctx.save();ctx.scale(scale,scale);ctx.translate(-view.x,-view.y);if(assets.map)ctx.drawImage(assets.map,0,0,game.width,game.height);else{ctx.fillStyle='#87aa79';ctx.fillRect(0,0,game.width,game.height);}ctx.fillStyle='#fff9e415';ctx.fillRect(0,0,game.width,game.height);if(game.stage.tint){ctx.fillStyle=game.stage.tint;ctx.fillRect(0,0,game.width,game.height);}drawLandmarks();
    for(const {text,x,y} of MAP_LABELS)label(text,x,y,'#55724a',13);
    for(const m of game.meetups){if(m.used)continue;const pulse=1+Math.sin(frameTime*.003)*.08;ctx.fillStyle='#ffec7f35';ctx.beginPath();ctx.arc(m.x,m.y,40*pulse,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#fffdd5d9';ctx.lineWidth=3;ctx.setLineDash([6,6]);ctx.beginPath();ctx.arc(m.x,m.y,33,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);emoji(m.icon,m.x,m.y-5,29);label('搭子集合',m.x,m.y+32,'#637329',11);}
    for(const g of game.gems){if(g.heal){emoji('💚',g.x,g.y,18);continue;}ctx.save();ctx.translate(g.x,g.y);ctx.rotate(Math.PI/4);ctx.fillStyle=g.val>3?'#edc64e':'#4ba49b';ctx.strokeStyle='#fffbc9';ctx.lineWidth=1.5;ctx.fillRect(-g.r,-g.r,g.r*2,g.r*2);ctx.strokeRect(-g.r,-g.r,g.r*2,g.r*2);ctx.restore();}
    for(const e of game.effects){if(e.kind!=='ring')continue;const t=1-e.life/e.maxLife;ctx.globalAlpha=(1-t)*.45;ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x,e.y,e.r*t,0,Math.PI*2);ctx.fill();ctx.globalAlpha=(1-t)*.85;ctx.strokeStyle=e.color;ctx.lineWidth=5;ctx.stroke();ctx.globalAlpha=1;if(e.icon)emoji(e.icon,e.x,e.y-30,35);}
    const actors=game.enemies.map(e=>({y:e.y,draw:()=>drawEnemy(e)}));if(active){if(game.clones>0){ctx.globalAlpha=.55;for(const sign of[-1,1])sprite(assets.hero,350,0,530,1254,game.player.x+sign*78,game.player.y-8,30,74,sign<0);ctx.globalAlpha=1;}game.team.forEach((c,i)=>actors.push({y:game.companionPosition(i).y,draw:()=>drawCompanion(c,i)}));actors.push({y:game.player.y,draw:()=>drawHero(game.player.x,game.player.y,Math.hypot(input().x,input().y)>0||game.player.dash>0)});}actors.sort((a,b)=>a.y-b.y).forEach(a=>a.draw());
    for(const b of game.enemyShots){ctx.fillStyle=b.color;ctx.strokeStyle='#fff5dc';ctx.lineWidth=2;ctx.beginPath();ctx.arc(b.x,b.y,b.r,0,Math.PI*2);ctx.fill();ctx.stroke();}
    for(const s of game.shots){ctx.fillStyle=s.color+'55';ctx.beginPath();ctx.arc(s.x,s.y,s.r*.75,0,Math.PI*2);ctx.fill();emoji(s.icon,s.x,s.y,s.r*1.8);}
    for(const e of game.effects){const t=1-e.life/e.maxLife;ctx.globalAlpha=1-t;if(e.kind==='text'){ctx.fillStyle=e.color;ctx.strokeStyle='#244c35';ctx.lineWidth=3;ctx.font='bold 17px "Space Grotesk",sans-serif';ctx.textAlign='center';ctx.strokeText(e.text,e.x,e.y);ctx.fillText(e.text,e.x,e.y);}else if(e.kind==='burst'){for(let a=0;a<6;a++){const angle=a*Math.PI/3;ctx.fillStyle=e.color;ctx.beginPath();ctx.arc(e.x+Math.cos(angle)*35*t,e.y+Math.sin(angle)*35*t,4*(1-t),0,Math.PI*2);ctx.fill();}}ctx.globalAlpha=1;}ctx.restore();
    if(damageFlash>0){ctx.strokeStyle=`rgba(217,86,70,${damageFlash*.7})`;ctx.lineWidth=16;ctx.strokeRect(0,0,w,h);}if(game.frenzy>0){ctx.strokeStyle='#d998c666';ctx.lineWidth=7;ctx.strokeRect(0,0,w,h);}if(active&&game.status==='running'&&w<600){const m=game.landmarks.find(m=>m.id===trackedLandmark&&m.state!=='complete')||game.meetups.filter(m=>!m.used).sort((a,b)=>Math.hypot(a.x-game.player.x,a.y-game.player.y)-Math.hypot(b.x-game.player.x,b.y-game.player.y))[0];if(m){const angle=Math.atan2(m.y-game.player.y,m.x-game.player.x);const mx=clamp(w/2+Math.cos(angle)*(w*.38),40,w-40),my=clamp(h/2+Math.sin(angle)*(h*.36),115,h-105);ctx.fillStyle='#153c32d9';rounded(mx-32,my-19,64,39,12);ctx.fill();emoji(m.icon,mx-12,my,20);ctx.save();ctx.translate(mx+15,my);ctx.rotate(angle);ctx.fillStyle='#ffdf6b';ctx.beginPath();ctx.moveTo(8,0);ctx.lineTo(-4,-5);ctx.lineTo(-4,5);ctx.fill();ctx.restore();}}
  }
  function processEvents(){for(const e of game.drain()){if(e.type==='upgrade')showChoices();if(e.type==='end')endScreen();if(e.type==='landmark')showLandmark();if(e.type==='stage-clear')stageClearScreen();if(e.type==='stage-start'){trackedLandmark=game.stage.landmark;landmarkSignature='';announcement('第 '+(game.stageIndex+1)+' 关 · '+game.stage.name+'，队伍一起出发！');}if(e.type==='challenge-start')announcement('榆中👻挑战开始！自由走位，坚持 10 秒。');if(e.type==='landmark-complete'){announcement(e.name+' · 完成！奇遇 +'+e.bonus+' 分');chime();}if(e.type==='hurt'){damageFlash=.55;beep(140,.08,'sawtooth',.025);}if(e.type==='boss')announcement('关底对手 · '+RIVALS[game.stage.boss].name+'来了！');if(e.type==='boss-defeated'){announcement(RIVALS[game.stage.boss].name+'退场！电量恢复 +30');chime();}if(e.type==='phase'&&e.phase<3)announcement(['','攻势增强 · 新对手加入','人越来越多，留心走位！'][e.phase]);if(e.type==='burst')beep(230,.18,'triangle',.04);if(e.type==='recruit'&&game.time>0)announcement(TYPE_MAP[e.id].name+'：'+TYPE_MAP[e.id].quote);}}
  function frame(now){const dt=Math.min(.05,((now-frameTime)||16.67)/1000);frameTime=now;game.step(dt,input());processEvents();damageFlash=Math.max(0,damageFlash-dt*2);announcementTimer-=dt;if(announcementTimer<=0)$('announcement').classList.remove('visible');uiClock-=dt;if(uiClock<=0){updateUI();uiClock=.1;}render();drawMinimap();requestAnimationFrame(frame);}
  Promise.all([['hero','assets/fengdou.png'],['map','assets/campus.png'],['companions','assets/companions.png'],['rivals','assets/rivals.png']].map(([key,url])=>new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{assets[key]=im;resolve();};im.onerror=()=>reject(new Error(url));im.src=url;}))).then(()=>{assetsReady=true;if(modal==='start'){$('start-button').disabled=false;$('start-button').textContent='出发！今天不鸽';}}).catch(()=>{if(modal==='start'){$('start-button').textContent='素材加载失败，点此重试';$('start-button').disabled=false;$('start-button').onclick=()=>location.reload();}});
  startScreen();resize();requestAnimationFrame(frame);
  const context=document.modelContext;
  if(context?.registerTool){const lifecycle=new AbortController();const tools=[{name:'read_fengdou_game',title:'查看 Fengdou 的校园冒险',description:'读取本局剩余时间、搭子队伍、技能和待选升级；不改变游戏状态。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>game.snapshot()},{name:'choose_fengdou_upgrade',title:'选择当前升级',description:'选择当前游戏已经显示的三选一升级。仅在升级选项出现时可用，编号 1 至 3。',inputSchema:{type:'object',properties:{choice:{type:'integer',minimum:1,maximum:3}},required:['choice'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!Number.isInteger(input.choice)||input.choice<1||input.choice>3||Object.keys(input).some(k=>k!=='choice'))throw new Error('choice 必须为 1、2 或 3');if(game.status!=='upgrade')throw new Error('当前没有待选升级');choose(input.choice-1);return game.snapshot();}}];for(const tool of tools){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
})();
